#!/bin/bash

rsync -rvz --progress --delete --exclude-from=/home/jason/public_html/lando-test/wp-content/plugins/core-functionality/rsync-exclude.txt ~/public_html/lando-test/wp-content/plugins/core-functionality/ ~/public_html/ucsc-pbsci/wp-content/plugins/core-functionality/