#!/bin/bash

rsync -rvz --progress --delete --exclude-from=/home/jason/Projects/local-pbsci/wp-content/plugins/core-functionality/rsync-exclude.txt ~/Projects/local-pbsci/wp-content/plugins/core-functionality/ ~/Projects/ucsc-pbsci/wp-content/plugins/core-functionality/